name: Build and push docker image
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: roseratu/hippotypose-landing:latest
          build-args: |
            PORT=3333
            NODE_ENV=production
            HOST=localhost
            LOG_LEVEL=info
            APP_KEY=tn3zT-5SYKlYxhiw_-mh24Bu9M8FCEQR
            SESSION_DRIVER=cookie
            DB_HOST=127.0.0.1
            DB_PORT=5432
            DB_USER=postgres
            DB_PASSWORD=Darkonis@72700
            DB_DATABASE=hippotypose
            SMTP_HOST=smtp.hostinger.com
            SMTP_PORT=465
            SMTP_USERNAME=hippotypose@corona-formation.fr
            SMTP_PASSWORD=Darkonisugoloic@72700
